openapi: 3.0.0
info:
  title: Sample API
  description: Sample API for demonstrating Swagger
  version: 1.0.0
servers:
  - url: http://localhost:4000
paths:
  /api:
    get:
      summary: Returns a list of items
      responses:
        '200':
          description: A list of items
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
